// Generated by CoffeeScript 1.10.0
(function() {
  window.enable_autocomplete_of_address = function(address_field) {
    address_field.autocomplete({
      source: function(request, response) {
        var data;
        data = {
          'query': request.term,
          'culture': 'de',
          'key': window.Config.BING_API_KEY
        };
        return jQuery.ajax({
          'url': 'https://dev.virtualearth.net/REST/v1/Locations',
          'data': data,
          'dataType': 'jsonp',
          'jsonp': 'jsonp',
          success: (function(_this) {
            return function(data) {
              var i, j, len, len1, names, ref, ref1, resource, resourceSet;
              names = [];
              ref = data.resourceSets;
              for (i = 0, len = ref.length; i < len; i++) {
                resourceSet = ref[i];
                ref1 = resourceSet.resources;
                for (j = 0, len1 = ref1.length; j < len1; j++) {
                  resource = ref1[j];
                  names.push(resource.name);
                }
              }
              return response(names);
            };
          })(this)
        });
      }
    });
  };

}).call(this);
