// Generated by CoffeeScript 2.5.1
(function() {
  //#
  // Get lat/lon for given address.
  // Uses Bing location service.

  // @param string query
  //  The address

  // @param function callback
  //  Callback function that takes long, lat and zip code.
  //#
  window.geocode_query = function(query, callback) {
    var data;
    data = {
      'query': query,
      'culture': 'de',
      'key': window.Config.BING_API_KEY
    };
    jQuery.ajax({
      'url': 'https://dev.virtualearth.net/REST/v1/Locations',
      'data': data,
      'dataType': 'jsonp',
      'jsonp': 'jsonp',
      success: function(data) {
        var latlon, ref, ref1, ref2, ref3, ref4, ref5, result, zip;
        result = (ref = data.resourceSets) != null ? (ref1 = ref[0]) != null ? (ref2 = ref1.resources) != null ? ref2[0] : void 0 : void 0 : void 0;
        latlon = result != null ? (ref3 = result.geocodePoints) != null ? (ref4 = ref3[0]) != null ? ref4.coordinates : void 0 : void 0 : void 0;
        zip = result != null ? (ref5 = result.address) != null ? ref5.postalCode : void 0 : void 0;
        if (((latlon != null ? latlon[0] : void 0) != null) && (latlon != null ? latlon[1] : void 0)) {
          callback(latlon[1], latlon[0], zip);
        }
      }
    });
  };

}).call(this);
